version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: enterprise_postgres
    environment:
      POSTGRES_DB: enterprise_platform
      POSTGRES_USER: enterprise_user
      POSTGRES_PASSWORD: enterprise_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database-init:/docker-entrypoint-initdb.d
    networks:
      - enterprise_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U enterprise_user -d enterprise_platform"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: enterprise_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - enterprise_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru

  # Database Service
  database-service:
    build:
      context: ./services/database-service
      dockerfile: Dockerfile
    container_name: enterprise_database_service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: enterprise_user
      POSTGRES_PASSWORD: enterprise_pass
      POSTGRES_DB: enterprise_platform
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVICE_PORT: 8002
    ports:
      - "8002:8002"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - enterprise_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # pgAdmin (Database Management UI)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: enterprise_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@enterprise.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - enterprise_network
    restart: unless-stopped
    depends_on:
      - postgres

  # Redis Commander (Redis Management UI)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: enterprise_redis_commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - enterprise_network
    restart: unless-stopped
    depends_on:
      - redis

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  enterprise_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
